//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.Contracts = new HashSet<Contract>();
            this.Statistics = new HashSet<Statistic>();
        }
    
        public int IdTour { get; set; }
        public string nameTour { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Statistic> Statistics { get; set; }
    }
}
